version: '3.7'

services:
    backend:
        container_name: own-cqrs-backend
        build:
            context: './'
            dockerfile: dev.Dockerfile
        volumes:
            - ./:/backend:delegated
            - /backend/node_modules
        ports:
            - '4000:4000'
